name = "back-end"
compatibility_date = "2023-12-01"

node_compat = true
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGE2OTAwNWYtZmFmZC00YjQ3LWFjMjgtZDRjOWMwMTFkYjcxIiwidGVuYW50X2lkIjoiZDE2NDVhYmFlNDM1NWQ1Y2ZiZWY4M2VjYzI0Yzg0MjdjMWUwMWQyMzBhYzhkYjA1YWJlNjI1ODgyN2I4YzA5NyIsImludGVybmFsX3NlY3JldCI6IjAzNzE5Y2E5LWQyZWYtNGY5Yi1iZTNmLWQzOTkyY2QxZjhkYyJ9.vR0uuMy0y8PSk4E0o24aJouKAVolesMVMLwAOZ4Y7yY"
JWT_SECRET = "myjwtsecret"
