name = "back-end"
compatibility_date = "2023-12-01"

node_compat = true
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTdhNzBjMjEtMTY3Ny00ZDBkLWI4NzctYjYwZmZkODYzMGZiIiwidGVuYW50X2lkIjoiMTI1Yjc5YzU1ZmU1NWI3ZTBhMDI0MWI2ZjAwNzQ3ZDBkYTAxYTgzN2E1ODUwMTU5OGI0MDM2ZTI3MmEwNTgwNiIsImludGVybmFsX3NlY3JldCI6ImY5ZTQ2ZWMxLTRmNDEtNDdhNC1iMjgwLTMxNDA5OGFmYmZlMCJ9.aZDqkhc6BYVM9QR-u7bgTFCuKp6S-bdwZLbOtZ-30RA"
JWT_SECRET = "myjwtsecret"
